# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-21 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=25)),
                ('mail_subject', models.CharField(max_length=255)),
                ('mail_body', djangocms_text_ckeditor.fields.HTMLField()),
            ],
        ),
    ]
