# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-23 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='activation_key',
            field=models.UUIDField(default='d3a8a2c9-3d5a-4daf-98b6-db2b625a4d37', editable=False),
            preserve_default=False,
        ),
    ]
